name: "Load Images to Database"

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  load_images:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v1
      - name: "Install Node.js"
        uses: actions/setup-node@v1
      - name: "Install npm dependencies"
        run: npm install
      - name: "Build project"
        run: npm run build
      - name: "Fetch images, then add to DB"
        run: npm start
        
        env:
          STORAGE_ENDPOINT: ${{ secrets.STORAGE_ENDPOINT }}
          STORAGE_ID: ${{ secrets.STORAGE_ID }}
          STORAGE_KEY: ${{ secrets.STORAGE_KEY }}
          STORAGE_BUCKET: ${{ secrets.STORAGE_BUCKET }}
          MONGO_URL: ${{ secrets.MONGO_URL }}
          MONGO_DB: ${{ secrets.MONGO_DB }}
          MONGO_COLL: ${{ secrets.MONGO_COLL }}
          CDN_URL: ${{ secrets.CDN_URL }}
